name: "Delete Old Workflow Runs"

on:
  schedule:
    - cron: "0 0 * * *" # Chạy vào lúc 0 giờ UTC mỗi ngày
  workflow_dispatch: # Cho phép chạy thủ công

jobs:
  del_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 5
